apiVersion: apps/v1
kind: Deployment
metadata:
  name: fpdealership
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fpdealership
  template:
    metadata:
      labels:
        app: fpdealership
    spec:
      containers:
        - name: dealership
          image: localhost:5000/fpdealership:latest
          imagePullPolicy: Always
          ports:
          - containerPort: 8000
            hostPort: 8000
            
